---
tmp_dir: "/ibex/user/naras0c/tmp"
output_dir: "/ibex/project/e3015/FLW_STG_multiomics/output"
data_table: "/ibex/project/e3015/FLW_STG_multiomics/sample_table.tsv"
input_dir:
  mg_assembly_input: "/ibex/project/e3015/FLW_STG_multiomics/output/metagenomics/preprocessing/"
  mg_binning_input: "/ibex/project/e3015/FLW_STG_multiomics/output/metagenomics/assembly/"
  mg_dereplication_input: "/ibex/project/e3015/FLW_STG_multiomics/output/metagenomics/binning"
  mg_annotation_input: "/ibex/project/e3015/FLW_STG_multiomics/output/metagenomics/dereplication"
  mg_quantification_input: "/ibex/project/e3015/FLW_STG_multiomics/output/metagenomics/preprocessing"


trimmomatic:
    adapters_path: "/ibex/user/naras0c/airport_surveillance/adapters.fa"

sortmerna:
    db_path: "/ibex/user/naras0c/sortmerna"
    filter_length: 20
    contaminant_fasta_path: "/ibex/user/naras0c/genomes/cabbage/ncbi_dataset/data/GCF_000695525.1/GCF_000695525.1_BOL_genomic.fna"
    contamination_name: "cabbage_genome"

mosdepth:
    threads: 12

binning:
  min_contig_length: 1500 ## Required by metabat2

concoct:
    threads: 40
    read_length: 250
    contig_split_length: 1000

metabat2:
    threads: 24

maxbin2:
    threads: 24

vamb:
    threads: 24

semibin:
    threads: 24
    environment_type: "wastewater"

semibin_multi_sample:
    threads: 36

magscot:
    folder: "/home/naras0c/repositories/github/MAGScoT"        

catbat:
    threads: 40
    db_path:
      gtdb: "/ibex/reference/KSL/cat/20231120/20231120_CAT_gtdb/db"
      nr: "/ibex/reference/KSL/cat/20231120/20231120_CAT_nr/db"
    tx_path:
      gtdb: "/ibex/reference/KSL/cat/20231120/20231120_CAT_gtdb/tax"
      nr: "/ibex/reference/KSL/cat/20231120/20231120_CAT_nr/tax"
    catpack_script: "/home/naras0c/repositories/github/CAT_pack/CAT_pack/CAT_pack"

drep:
    completeness: 75
    contamination: 25
    strain_heterogeneity_weight: 1
    P_ani: 0.9
    S_ani: 0.9

bakta:
    db_path: "/ibex/user/naras0c/databases/bakta/db"

salmon:
    min_assigned_frags: 1
    catalogues: 
       MAG_annotation_dir: 
         path: "/ibex/project/e3015/FLW_STG_multiomics/output/metagenomics/annotation/bakta"
         extension: "ffn"
       MAG_path_dir: 
         path: "/ibex/project/e3015/FLW_STG_multiomics/output/metagenomics/dereplication/dereplicated_bins/dereplicated_genomes/"
         extension: "fasta"

coverm:
    genomes_dir: "/ibex/project/e3015/FLW_STG_multiomics/output/metagenomics/dereplication/dereplicated_bins/dereplicated_genomes"
    threads: 24


